tests:
    Pages should not become slower:
        path: /.*
        assertions:
            - "percent(main.wall_time) < 10%"
            - "percent(main.memory) < 10%"
    Pages should not consume too much memory:
        path: /
        assertions:
            - main.memory < 50M
            - main.peak_memory < 75M
    Homepage should not do too many SQL queries:
        path: /
        assertions:
            - metrics.sql.queries.count <= 12
    Checkout pages:
        path: /checkout/.*
        assertions:
            - metrics.output.network_out < 100KB

scenarios:
    Home:
        - path: /
          warmup: true

    Cart:
        - path: /checkout/cart/
          warmup: true

    Checkout:
        - path: /checkout/
          warmup: true

    ### Scenarios below must be uncommented after "percent" assertions will be fixed
    #Search:
    #    - /catalogsearch/result/index/?q=Simple&mycolor=14
    #    - /catalogsearch/result/?q=Simple

    #Customer login/signup:
    #    - /customer/account/login/
    #    - /customer/account/create/
