#log:
#  slack:
#      token: "<your-slack-token>"
#      channel: "<your-slack-channel>"
#      username: "SlackHandler"
#      min_level: "info"
#  email:
#      to: <your-email>
#      from: <your-email>
#      subject: "Log notification from Magento Cloud"
#      min_level: "notice"
#stage:
#  global:
#      SCD_THREADS: 1
#      SCD_EXCLUDE_THEMES: ""
#      SCD_STRATEGY: ""
#      SKIP_SCD: false
#      VERBOSE_COMMANDS: ""
#  build:
#      SCD_COMPRESSION_LEVEL: 6
#  deploy:
#      SCD_COMPRESSION_LEVEL: 4
#      QUEUE_CONFIGURATION: { }
#      SEARCH_CONFIGURATION: { }
#      CACHE_CONFIGURATION: { }
#      SESSION_CONFIGURATION: { }
#      CRON_CONSUMERS_RUNNER: { }
#      CLEAN_STATIC_FILES: true
#      STATIC_CONTENT_SYMLINK: true
#      UPDATE_URLS: true
