<?php
/**
 * Same as obsolete_classes.php, but specific to Magento EE
 *
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

return [
    ['Magento\CatalogEvent\Block\Adminhtml\Event\Grid'],
    ['Magento\AdvancedCheckout\Block\Adminhtml\Sku\Errors\Grid'],
    [
        'Magento\CustomAttributeManagement\Block\Form\Template',
        'Magento\Framework\View\Element\Template with renderers as child blocks'
    ],
    ['Magento\AdminNotification\Controller\Adminhtml\Survey', 'Magento\Install\Controller\Adminhtml\Survey'],
    [
        'Magento\AdminNotification\Controller\Adminhtml\Survey\Index',
        'Magento\Install\Controller\Adminhtml\Survey\Index'
    ],
    ['Magento\AdminNotification\Model\System\Message\Survey', 'Magento\Install\Model\System\Message\Survey'],
    ['Magento\AdminNotification\Model\Survey', 'Magento\Install\Model\Survey'],
    ['Magento\AdvancedCheckout\Exception'],
    ['Magento\CustomerCustomAttributes\Block\Form\Renderer\AbstractRenderer'],
    ['Magento\CustomerCustomAttributes\Block\Form\Renderer\Boolean'],
    ['Magento\CustomerCustomAttributes\Block\Form\Renderer\Date'],
    ['Magento\CustomerCustomAttributes\Block\Form\Renderer\File'],
    ['Magento\CustomerCustomAttributes\Block\Form\Renderer\Image'],
    ['Magento\CustomerCustomAttributes\Block\Form\Renderer\Multiline'],
    ['Magento\CustomerCustomAttributes\Block\Form\Renderer\Multiselect'],
    ['Magento\CustomerCustomAttributes\Block\Form\Renderer\Select'],
    ['Magento\CustomerCustomAttributes\Block\Form\Renderer\Text'],
    ['Magento\CustomerCustomAttributes\Block\Form\Renderer\Textarea'],
    ['Magento\CustomerCustomAttributes\Block\Form\Template'],
    ['Magento\GiftCardAccount\Block\Adminhtml\Giftcardaccount\Grid'],
    ['Magento\GiftCard\Block\Email\Generated'],
    ['Magento\GiftRegistry\Block\Adminhtml\Customer\View'],
    ['Magento\GiftRegistry\Block\Adminhtml\Giftregistry\Grid'],
    ['Magento\ScheduledImportExport\Block\Adminhtml\Scheduled\Operation\Grid'],
    ['Magento\Invitation\Block\Adminhtml\Invitation\Grid'],
    ['Magento\Invitation\Block\Adminhtml\Report\Invitation\Customer\Grid'],
    ['Magento\Invitation\Block\Adminhtml\Report\Invitation\Order\Grid'],
    ['Magento\Invitation\Block\Adminhtml\Report\Invitation\General\Grid'],
    ['Magento\Logging\Block\Adminhtml\Archive\Grid'],
    ['Magento\Logging\Block\Adminhtml\Index\Grid'],
    ['Magento\Pci\Block\Adminhtml\Locks\Grid'],
    ['Magento\Pci\Block\Adminhtml\Crypt\Key\Edit.php'],
    ['Magento\Pci\Block\Adminhtml\Crypt\Key\Form.php'],
    ['Magento\Pci\Block\Adminhtml\Locks.php'],
    ['Magento\Pci\Controller\Adminhtml\Crypt\Key.php'],
    ['Magento\Pci\Controller\Adminhtml\Crypt\Key\Index.php'],
    ['Magento\Pci\Controller\Adminhtml\Crypt\Key\Save.php'],
    ['Magento\Pci\Controller\Adminhtml\Locks.php'],
    ['Magento\Pci\Controller\Adminhtml\Locks\Grid.php'],
    ['Magento\Pci\Controller\Adminhtml\Locks\Index.php'],
    ['Magento\Pci\Controller\Adminhtml\Locks\MassUnlock.php'],
    ['Magento\Pci\Model\Backend\Observer.php'],
    ['Magento\Pci\Model\Observer.php'],
    ['Magento\Pci\Model\Resource\Admin\User.php'],
    ['Magento\Pci\Model\Resource\Key\Change.php'],
    ['Magento\Pci\Model\System\Config\Source\Password.php'],
    ['Magento\Pci\Setup\InstallSchema.php'],
    ['Magento\Reminder\Block\Adminhtml\Reminder\Grid'],
    ['Magento\Reward\Block\Adminhtml\Reward\Rate\Grid'],
    ['Magento\Reward\Block\Customer\Account', 'Magento\Reward\Block\Customer\AccountLink'],
    ['Magento\Reward\Model\Reward\Balance\Exception'],
    ['Magento\Solr\Model\Indexer\Price'],
    ['Magento\Solr\Model\ResourceModel\Suggestions'],
    ['Magento\TargetRule\Block\Adminhtml\Targetrule\Grid'],
    ['Magento\GiftWrapping\Block\Adminhtml\Giftwrapping\Grid'],
    ['Magento\CustomerSegment\Model\ResourceModel\Helper\Mssql'],
    ['Magento\Logging\Model\ResourceModel\Helper\Mssql'],
    ['Magento\Reminder\Model\ResourceModel\Helper\Mssql'],
    ['Magento\SalesArchive\Model\ResourceModel\Helper\Mssql'],
    ['Magento\CustomerSegment\Model\ResourceModel\Helper\Oracle'],
    ['Magento\Logging\Model\ResourceModel\Helper\Oracle'],
    ['Magento\Reminder\Model\ResourceModel\Helper\Oracle'],
    ['Magento\SalesArchive\Model\ResourceModel\Helper\Oracle'],
    [
        'Magento\Solr\Controller\Adminhtml\Search\System\Config\TestConnection\Ping',
        'Magento\AdvancedSearch\Controller\Adminhtml\Search\System\Config\TestConnection'
    ],
    ['Magento\Solr\Helper\ClientOptionsInterface', 'Magento\AdvancedSearch\Model\Client\ClientOptionsInterface'],
    ['Magento\Solr\Model\Client\FactoryInterface', 'Magento\AdvancedSearch\Model\Client\ClientFactoryInterface'],
    ['Magento\Solr\Model\ObjectManager\Configurator'],
    ['Magento\Solr\Test\Unit\Controller\Adminhtml\Search\System\Config\TestConnection\PingTest'],
    [
        'Magento\Elasticsearch\Test\Unit\Model\SearchAdapter\ConnectionManagerTest',
        'Magento\Elasticsearch\Test\Unit\SearchAdapter\ConnectionManagerTest'
    ],
    [
        'Magento\Solr\Model\ResourceModel\Index',
        'Magento\AdvancedSearch\Model\ResourceModel\Index'
    ],
    [
        'Magento\Solr\Test\Unit\Model\Indexer\Fulltext\Plugin\CustomerGroupTest',
        'Magento\AdvancedSearch\Test\Unit\Model\Indexer\Fulltext\Plugin\CustomerGroupTest'
    ],
    [
        'Magento\Solr\Model\Indexer\Fulltext\Plugin\CustomerGroup',
        'Magento\AdvancedSearch\Model\Indexer\Fulltext\Plugin\CustomerGroup'
    ],
    ['Varien_Db_Statement_Pdo_Mssql'],
    ['Varien_Db_Adapter_Pdo_Mssql'],
    ['Magento\GiftCard\CustomerData\GiftCardItem'],
    ['Mage_Backup_Model_Resource_Helper_Mssql'],
    ['Mage_Catalog_Model_Resource_Helper_Mssql'],
    ['Mage_CatalogSearch_Model_Resource_Helper_Mssql'],
    ['Mage_Core_Model_Resource_Helper_Mssql'],
    ['Mage_Eav_Model_Resource_Helper_Mssql'],
    ['Mage_ImportExport_Model_Resource_Helper_Mssql'],
    ['Mage_Log_Model_Resource_Helper_Mssql'],
    ['Mage_Reports_Model_Resource_Helper_Mssql'],
    ['Mage_Sales_Model_Resource_Helper_Mssql'],
    ['Mage_Install_Block_Db_Type_Mssql'],
    ['Mage_Install_Model_Installer_Db_Mssql'],
    ['Varien_Db_Statement_Sqlsrv'],
    ['Mage_Backup_Model_Resource_Helper_Oracle'],
    ['Mage_Catalog_Model_Resource_Helper_Oracle'],
    ['Mage_CatalogSearch_Model_Resource_Helper_Oracle'],
    ['Mage_Eav_Model_Resource_Helper_Oracle'],
    ['Mage_ImportExport_Model_Resource_Helper_Oracle'],
    ['Mage_Log_Model_Resource_Helper_Oracle'],
    ['Mage_Reports_Model_Resource_Helper_Oracle'],
    ['Mage_Sales_Model_Resource_Helper_Oracle'],
    ['Mage_Core_Model_Resource_Helper_Oracle'],
    ['Varien_Db_Adapter_Oracle'],
    ['Mage_Install_Block_Db_Type_Oracle'],
    ['Mage_Install_Model_Installer_Db_Oracle'],
    ['Magento\Queue\Model\Queue'],
    ['Magento\Queue\Model\AddException'],
    ['Magento\Queue\Model\Config'],
    ['Magento\Queue\Model\Config\Gearman'],
    ['Magento\Queue\Model\Event\Handler'],
    ['Magento\Queue\Model\Event\Invoker\Asynchronous'],
    ['Magento\Queue\Model\Resource\Task'],
    ['Magento\Queue\Model\Task'],
    ['Magento\Queue\Model\TaskRepository'],
    ['Magento\Rma\Block\Order\Guest'],
    ['Magento\Rma\Block\Order\Info'],
    ['Magento\Rma\Block\Returns\Info'],
    ['Magento\MultipleWishlist\Block\Links', 'Magento\MultipleWishlist\Block\Link'],
    ['Magento\Reminder\Model\ResourceModel\Setup', '\Magento\Core\Model\Resource\Setup'],
    ['Magento\FullPageCache\Model\Http\Handler'],
    ['Magento\CustomerSegment\Model\ResourceModel\Helper\Mysql4', 'Magento\CustomerSegment\Model\ResourceModel\Helper'],
    ['Magento\SalesArchive\Model\ResourceModel\Helper\Mysql4', 'Magento\SalesArchive\Model\ResourceModel\Helper'],
    ['Magento\Solr\Model\Client\Solr\Factory'],
    ['Magento\Solr\Model\Client\SolrClient\Factory'],
    ['Magento\License', 'Magento_License'],
    [
        'Magento\PricePermissions\Controller\Adminhtml\Product\Initialization\Helper\Plugin\HandlerInterface',
        'Magento\Catalog\Controller\Adminhtml\Product\Initialization\Helper\HandlerInterface'
    ],
    [
        'Magento\PricePermissions\Controller\Adminhtml\Product\Initialization\Helper\Plugin\Handler\ProductType\Configurable',
        'Magento\ConfigurableProduct\Controller\Adminhtml\Product\Initialization\Helper\Plugin\Handler\ProductType\Configurable'
    ],
    ['Magento\FullPageCache\App\*'],
    ['Magento\FullPageCache\Block\*'],
    ['Magento\FullPageCache\Controller\Request'],
    ['Magento\FullPageCache\Helper\*'],
    ['Magento\FullPageCache\Model\*'],
    ['Magento\JobQueue'], // unused library code which was removed
    ['Magento\SalesArchive\Block\Adminhtml\Sales\Order\View\Tab\Shipments'],
    ['Magento\SalesArchive\Block\Adminhtml\Sales\Order\View\Tab\Invoices'],
    ['Magento\SalesArchive\Block\Adminhtml\Sales\Order\View\Tab\Creditmemos'],
    ['Magento\SalesArchive\Block\Adminhtml\Sales\Archive\Order\Creditmemo\Grid'],
    ['Magento\SalesArchive\Block\Adminhtml\Sales\Archive\Order\Invoice\Grid'],
    ['Magento\SalesArchive\Block\Adminhtml\Sales\Archive\Order\Shipment\Grid'],
    ['Magento\TargetRule\Model\ResourceModel\Setup'],
    ['Magento\Enterprise\Model\Resource\Setup\Migration'],
    ['Magento\SalesRule\Helper\Data'],
    ['Magento\Enterprise\Helper\Data'],
    ['Magento\Pci\Helper\Data'],
    ['Magento\SalesArchive\Helper\Data'],
    ['Magento\WebsiteRestriction\Helper\Data'],
    ['Magento\CustomerCustomAttributes\Block\Account\RegisterLink'],
    ['Magento\Invitation\Model\Observer','Magento\Invitation\Model\Logging'],
    ['Magento\Reward\Model\Observer'],
    ['Magento\WebsiteRestriction\Model\Observer'],
    ['Magento\MultipleWishlist\Block\Rss'],
    ['Magento\VersionsCms\Model\ResourceModel\Hierarchy\Lock'],
    ['Magento\VersionsCms\Model\Hierarchy\Lock'],
    [
        'Magento\CatalogRule\Block\Adminhtml\Promo\Widget\Chooser\Daterange',
        'Magento\CustomerSegment\Block\Adminhtml\Widget\Chooser\Daterange'
    ],
    ['Magento\Pci\Model\Encryption', 'Magento\Framework\Encryption\Encryptor'],
    ['Magento\Search\Block\SearchData', 'Magento\AdvancedSearch\Block\SearchData'],
    ['Magento\Search\Block\Recommendations', 'Magento\AdvancedSearch\Block\Recommendations'],
    ['Magento\Search\Block\SearchDataInterface', 'Magento\AdvancedSearch\Block\SearchDataInterface'],
    ['Magento\Search\Block\Suggestions', 'Magento\AdvancedSearch\Block\Suggestions'],
    ['Magento\Search\Model\SearchDataProvider', 'Magento\AdvancedSearch\Model\SearchDataProvider'],
    ['Magento\Search\Model\SearchDataProviderInterface', 'Magento\AdvancedSearch\Model\SearchDataProviderInterface'],
    ['Apache_Solr_Document'],
    ['Apache_Solr_Response'],
    ['Apache_Solr_Service'],
    ['Apache_Solr_Service_Balancer'],
    [
        'Magento\Solr\Model\Layer\AdvancedSearch\Context',
        'Magento\Solr\Model\Layer\Category\Context',
        'Magento\Solr\Model\Layer\Search\Context'
    ],
    ['Magento\SalesArchive\Model\ResourceModel\Setup', 'Magento\SalesArchive\Setup\InstallData'],
    ['Magento\WebsiteRestriction\Model\Resource\Setup', 'Magento\WebsiteRestriction\Setup\InstallData'],
    ['Magento\VersionsCms\Model\ResourceModel\Setup', 'Magento\VersionsCms\Setup\InstallData'],
    ['Magento\Reward\Model\ResourceModel\Setup', 'Magento\Reward\Setup\InstallData'],
    ['Magento\GiftWrapping\Model\ResourceModel\Setup', 'Magento\GiftWrapping\Setup\InstallData'],
    ['Magento\GiftRegistry\Model\ResourceModel\Setup', 'Magento\GiftRegistry\Setup\InstallData'],
    ['Magento\GiftCardAccount\Model\ResourceModel\Setup', 'Magento\GiftCardAccount\Setup\InstallData'],
    ['Magento\Enterprise\Model\Resource\Setup', 'Magento\Enterprise\Setup\InstallData'],
    ['Magento\CustomerSegment\Model\ResourceModel\Setup', 'Magento\CustomerSegment\Setup\InstallData'],
    ['Magento\CustomerBalance\Model\ResourceModel\Setup', 'Magento\CustomerBalance\Setup\InstallData'],
    ['Magento\CatalogEvent\Model\ResourceModel\Setup', 'Magento\CatalogEvent\Setup\InstallData'],
    ['Magento\Banner\Model\ResourceModel\Setup', 'Magento\Banner\Setup\InstallData'],
    ['Magento\Rma\Model\ResourceModel\Setup', 'Magento\Rma\Setup\RmaSetup'],
    ['Magento\AdminGws\Controller\Exception'],
    ['Magento\TargetRule\Exception'],
    ['Magento\ScalableCheckout\Model\Exception'],
    ['Magento\ScalableCheckout\Model\Resource\Quote\Collection'],
    ['Magento\ScalableCheckout\Model\Resource\Quote\CollectionFactory'],
    ['Magento\Reward\Model\Observer\CustomerRegister'],
    ['Magento\Reward\Model\Observer\ApplyRewardSalesrulePoints'],
    ['Magento\GiftWrapping\Model\Plugin\DataProcessor'],
    ['Magento\PricePermissions\Controller\Adminhtml\ConfigurableProduct\Product\GenerateVariations\Plugin\Index'],
    ['Magento\VersionsCms\Model\Observer', 'corresponding classes in Magento\VersionsCms\Observer\*'],
    [
        'Magento\CustomerCustomAttributes\Model\Observer',
        'corresponding classes in Magento\CustomerCustomAttributes\Observer\*'
    ],
    ['Magento\CustomerSegment\Model\Observer'],
    ['Magento\GiftCard\Model\Observer', 'corresponding classes in Magento\GiftCard\Observer\*'],
    ['Magento\GiftCardAccount\Model\Observer', 'corresponding classes in Magento\GiftCardAccount\Observer\*'],
    ['Magento\CatalogEvent\Model\Observer', 'corresponding classes in Magento\CatalogEvent\Observer\*'],
    ['Magento\CatalogPermissions\Model\Observer'],
    ['Magento\CustomerBalance\Model\Observer', 'corresponding classes in Magento\CustomerBalance\Observer\*'],
    ['Magento\GiftWrapping\Model\Observer', 'corresponding classes in Magento\GiftWrapping\Observer\*'],
    ['Magento\GiftRegistry\Model\Observer', 'corresponding classes in Magento\GiftRegistry\Observer\*'],
    ['Magento\TargetRule\Model\ResourceModel\Index\AbstractIndex'],
    ['Magento\TargetRule\Model\ResourceModel\Index\Crosssell'],
    ['Magento\TargetRule\Model\ResourceModel\Index\Related'],
    ['Magento\TargetRule\Model\ResourceModel\Index\Upsell'],
    ['Magento\Invitation\Controller\Customer\Account\ResetPassword'],
    ['Magento\PricePermissions\Block\Adminhtml\ConfigurableProduct\Product\Edit\Tab\Super\Config\Plugin\Matrix'],
    ['Magento\CustomerBalance\Observer\QuoteCollectTotalsBeforeObserver'],
    ['Magento\GiftCardAccount\Model\Plugin\CartTotalRepository'],
    ['Magento\GiftCardAccount\Observer\QuoteCollectTotalsBefore'],
    ['Magento\GiftCardAccount\Test\Unit\Model\Plugin\CartTotalRepositoryTest'],
    ['Magento\GiftWrapping\Model\Plugin\TotalProcessor'],
    ['Magento\GiftWrapping\Observer\QuoteCollectTotalsBefore'],
    ['Magento\GiftWrapping\Test\Unit\Observer\QuoteCollectTotalsBeforeTest'],
    ['Magento\Reward\Model\Observer\QuoteCollectTotalsBefore'],
    ['Magento\Reward\Test\Unit\Model\Observer\QuoteCollectTotalsBeforeTest'],
    ['Magento\TargetRule\Model\Observer', '\Magento\TargetRule\Observer\*'],
    ['Magento\VersionsCms\Model\Backend\Observer', 'Magento\VersionsCms\Observer\Backend\*'],
    ['Magento\PersistentHistory\Observer\SkipWebsiteRestrictionObserver'],
    [
        'Magento\VersionsCms\Model\Backend\PrepareFormObserver',
        'Magento\VersionsCms\Observer\Backend\PrepareFormObserver'
    ],
    ['Magento\VersionsCms\Api\Data\PageRevisionInterface'],
    ['Magento\VersionsCms\Api\Data\PageRevisionSearchResultsInterface'],
    ['Magento\VersionsCms\Api\Data\PageVersionInterface'],
    ['Magento\VersionsCms\Api\Data\PageVersionSearchResultsInterface'],
    ['Magento\VersionsCms\Api\PageRevisionManagementInterface'],
    ['Magento\VersionsCms\Api\PageRevisionRepositoryInterface'],
    ['Magento\VersionsCms\Api\PageVersionRepositoryInterface'],
    ['Magento\VersionsCms\App\Action\Plugin\Design'],
    ['Magento\VersionsCms\App\FrontController\AdminSessionPlugin'],
    ['Magento\VersionsCms\App\Preview'],
    ['Magento\VersionsCms\Block\Adminhtml\Cms\Page'],
    ['Magento\VersionsCms\Block\Adminhtml\Cms\Page\Edit\Tab\Versions'],
    ['Magento\VersionsCms\Block\Adminhtml\Cms\Page\Preview\Form'],
    ['Magento\VersionsCms\Block\Adminhtml\Cms\Page\Preview\Revision'],
    ['Magento\VersionsCms\Block\Adminhtml\Cms\Page\Revision\Edit'],
    ['Magento\VersionsCms\Block\Adminhtml\Cms\Page\Revision\Edit\Form'],
    ['Magento\VersionsCms\Block\Adminhtml\Cms\Page\Revision\Edit\Info'],
    ['Magento\VersionsCms\Block\Adminhtml\Cms\Page\Revision\Edit\Tab\Content'],
    ['Magento\VersionsCms\Block\Adminhtml\Cms\Page\Revision\Edit\Tab\Design'],
    ['Magento\VersionsCms\Block\Adminhtml\Cms\Page\Revision\Edit\Tab\Meta'],
    ['Magento\VersionsCms\Block\Adminhtml\Cms\Page\Revision\Edit\Tabs'],
    ['Magento\VersionsCms\Block\Adminhtml\Cms\Page\Version\Edit'],
    ['Magento\VersionsCms\Block\Adminhtml\Cms\Page\Version\Edit\Form'],
    ['Magento\VersionsCms\Block\Adminhtml\Cms\Page\Version\Edit\Revisions'],
    ['Magento\VersionsCms\Controller\Adminhtml\Cms\Page\MassDeleteVersions'],
    ['Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Revision\Delete'],
    ['Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Revision\Edit'],
    ['Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Revision\MassDeleteVersions'],
    ['Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Revision\NewAction'],
    ['Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Revision\Preview'],
    ['Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Revision\Publish'],
    ['Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Revision\Save'],
    ['Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Revision\Versions'],
    ['Magento\VersionsCms\Controller\Adminhtml\Cms\Page\RevisionInterface'],
    ['Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Version\Delete'],
    ['Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Version\Edit'],
    ['Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Version\MassDeleteRevisions'],
    ['Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Version\MassDeleteVersions'],
    ['Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Version\NewAction'],
    ['Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Version\Revisions'],
    ['Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Version\Save'],
    ['Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Version\VersionProvider'],
    ['Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Version\Versions'],
    ['Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Versions'],
    ['Magento\VersionsCms\Controller\Page\Revision\Drop'],
    ['Magento\VersionsCms\Model\Config'],
    ['Magento\VersionsCms\Model\Increment'],
    ['Magento\VersionsCms\Model\Page\Revision'],
    ['Magento\VersionsCms\Model\Page\RevisionManagement'],
    ['Magento\VersionsCms\Model\Page\RevisionProvider'],
    ['Magento\VersionsCms\Model\Page\RevisionRepository'],
    ['Magento\VersionsCms\Model\Page\Version'],
    ['Magento\VersionsCms\Model\Page\VersionRepository'],
    ['Magento\VersionsCms\Model\Plugin\CmsPage'],
    ['Magento\VersionsCms\Model\ResourceModel\Page\Collection\AbstractCollection'],
    ['Magento\VersionsCms\Model\ResourceModel\Page\Revision'],
    ['Magento\VersionsCms\Model\ResourceModel\Page\Revision\Collection'],
    ['Magento\VersionsCms\Model\ResourceModel\Page\Version'],
    ['Magento\VersionsCms\Model\ResourceModel\Page\Version\Collection'],
    ['Magento\VersionsCms\Model\Source\Versioning'],
    ['Magento\VersionsCms\Observer\Backend\AdminUserDeleteAfterObserver'],
    ['Magento\Framework\MessageQueue\Config\Reader\Xml\Converter\DeprecatedFormat'],
    ['Magento\VersionsCms\Observer\Backend\PrepareFormObserver'],
    ['Magento\VersionsCms\Observer\Backend\RemoveVersionCallback'],
    ['Magento\VersionsCms\Setup\InstallData'],
    ['Magento\VersionsCms\Block\Adminhtml\Cms\Page\Preview\Buttons'],
    ['Magento\Framework\MessageQueue\Config\Converter', 'Magento\Framework\MessageQueue\Config\Reader\Xml\CompositeConverter'],
    ['Magento\Framework\MessageQueue\Config\Reader', 'Magento\Framework\MessageQueue\Config\Reader\Xml'],
    ['Magento\Framework\MessageQueue\PublisherFactory'],
    ['Magento\Framework\MessageQueue\PublisherProxy'],
    ['Magento\CatalogEvent\Block\Adminhtml\Catalog\Category\Edit\Buttons'],
    ['Magento\CatalogPermissions\Model\Adminhtml\AddPermissionTabOnCategoryEditPageObserver'],
    ['Magento\Banner\Block\Adminhtml\Permission\Monitor'],
    [
        'Magento\PromotionPermissions\Block\Adminhtml\Promo\Catalog\Edit\Plugin',
        'Magento\PromotionPermissions\Block\Adminhtml\Promo\Catalog\Edit\GenericButton\Plugin'
    ],
    ['Magento\Staging\Controller\Adminhtml\Entity\DeleteAbstract'],
    ['Magento\Staging\Controller\Adminhtml\Entity\SaveAbstract'],
    ['Magento\SalesArchive\Observer\SalesUpdateGridRecordsObserver']
];
