import { Product, StoreIdentity } from '../types/commerce';

export const DEFAULT_STORE_IDENTITY: StoreIdentity = {
  storeName: 'Al-Madina Luxury & Tech Hub',
  tagline: 'Premium Electronics & Lifestyle • Dubai & UAE Delivery',
  announcementText: '🌟 Ramadan & Summer Mega Sale: FREE Amazon Delivery across UAE on orders over AED 250 • Pay in 4 with Tabby',
  logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&h=80&fit=crop&q=80',
  faviconUrl: '/favicon.ico',
  primaryColor: '#0284c7', // Modern sky/cyan blue
  accentColor: '#f59e0b', // Luxury gold amber
  supportEmail: 'care@almadinahub.ae',
  supportPhone: '+971 4 800 2345',
  whatsappNumber: '+971501928374',
  companyLegalName: 'Al-Madina E-Commerce & Retail Solutions LLC',
  tradeLicenseNumber: 'DED-CN-8921049',
  uaeTrn: '100293847500003', // 15-digit UAE TRN
  address: 'Level 14, Boulevard Plaza Tower 1, Sheikh Mohammed Bin Rashid Blvd, Downtown Dubai, UAE',
  freeShippingThresholdAed: 250,
  defaultCurrency: 'AED',
  heroBadgeText: 'Dubai Central Warehouse • Same-Day Dispatch',
  heroTitle: 'Next-Gen Tech & Luxury Essentials',
  heroHighlight: 'Delivered Across UAE',
  heroDescription:
    'Official TRA-approved devices with manufacturer warranties. Enjoy Amazon Logistics delivery, 5% UAE VAT Invoices, and split your bill in 4 with Tabby.',
  heroCtaPrimaryText: 'Explore Catalog',
  heroCtaPrimaryLink: '/shop',
  heroCtaSecondaryText: 'Admin Control Center',
  heroCtaSecondaryLink: '/admin',
};

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    sku: 'IPH-16PM-512',
    barcode: '194253982104',
    title: 'Apple iPhone 16 Pro Max - 512GB (Titanium Edition)',
    slug: 'apple-iphone-16-pro-max-512gb',
    description:
      'Engineered with Grade 5 Titanium, featuring the groundbreaking A18 Pro chip, 48MP Fusion camera system with 5x Telephoto optical zoom, and next-generation Action Button. Direct UAE TRA approved model with FaceTime support.',
    shortDescription: 'Grade 5 Titanium, A18 Pro chip, 48MP Camera, UAE TRA Compliant.',
    category: 'Smartphones',
    brand: 'Apple',
    basePriceAed: 5499,
    compareAtPriceAed: 5999,
    costPriceAed: 4800,
    featuredImage: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&auto=format&fit=crop&q=80',
    ],
    stock: 24,
    lowStockThreshold: 5,
    hasVariants: true,
    variants: [
      {
        id: 'var-1-1',
        sku: 'IPH-16PM-512-NT',
        name: 'Natural Titanium / 512GB',
        options: { Color: 'Natural Titanium', Storage: '512GB' },
        priceAdjustmentAed: 0,
        stock: 12,
      },
      {
        id: 'var-1-2',
        sku: 'IPH-16PM-512-DT',
        name: 'Desert Titanium / 512GB',
        options: { Color: 'Desert Titanium', Storage: '512GB' },
        priceAdjustmentAed: 0,
        stock: 8,
      },
      {
        id: 'var-1-3',
        sku: 'IPH-16PM-1TB-BL',
        name: 'Black Titanium / 1TB',
        options: { Color: 'Black Titanium', Storage: '1TB' },
        priceAdjustmentAed: 800,
        stock: 4,
      },
    ],
    tags: ['Flagship', 'Apple', '5G', 'Best Seller', 'UAE Warranty'],
    rating: 4.9,
    reviewCount: 128,
    reviews: [
      {
        id: 'rev-1',
        author: 'Tariq Al Mansoori',
        rating: 5,
        date: '2026-08-15',
        title: 'Super fast Dubai same day delivery!',
        comment: 'Received the phone within 4 hours in Downtown Dubai. Genuine UAE version with official Apple warranty. Tabby 4x payment was seamless.',
        verifiedPurchase: true,
        location: 'Dubai, UAE',
      },
      {
        id: 'rev-2',
        author: 'Vikram Sharma',
        rating: 5,
        date: '2026-08-10',
        title: 'Best price in UAE and fast shipping to Abu Dhabi',
        comment: 'Saved over AED 400 compared to mall stores. Delivered safely via Amazon Logistics.',
        verifiedPurchase: true,
        location: 'Abu Dhabi, UAE',
      },
    ],
    amazonAsin: 'B0CHX19NYW',
    amazonPriceAed: 5599,
    odooProductId: 101,
    isFeatured: true,
    isTrending: true,
    isFlashDeal: true,
    flashDealEndsAt: new Date(Date.now() + 48 * 3600000).toISOString(),
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-08-20T12:00:00Z',
  },
  {
    id: 'prod-2',
    sku: 'SNY-WH1000XM5',
    barcode: '4548736132566',
    title: 'Sony WH-1000XM5 Wireless Noise-Canceling Headphones',
    slug: 'sony-wh-1000xm5-wireless-noise-canceling-headphones',
    description:
      'Industry-leading noise canceling with two processors and 8 microphones. Ultra-comfortable lightweight design with soft fit leather, 30-hour battery life, and crystal-clear hands-free calling with AI voice pickup.',
    shortDescription: 'Industry-leading ANC, 30h battery, High-Res Audio & Speak-to-Chat.',
    category: 'Audio',
    brand: 'Sony',
    basePriceAed: 1199,
    compareAtPriceAed: 1499,
    costPriceAed: 950,
    featuredImage: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
    ],
    stock: 45,
    lowStockThreshold: 8,
    hasVariants: true,
    variants: [
      {
        id: 'var-2-1',
        sku: 'SNY-WH1000XM5-BLK',
        name: 'Midnight Black',
        options: { Color: 'Black' },
        priceAdjustmentAed: 0,
        stock: 30,
      },
      {
        id: 'var-2-2',
        sku: 'SNY-WH1000XM5-SLV',
        name: 'Platinum Silver',
        options: { Color: 'Silver' },
        priceAdjustmentAed: 0,
        stock: 15,
      },
    ],
    tags: ['ANC', 'Audio', 'Travel', 'Wireless'],
    rating: 4.8,
    reviewCount: 94,
    amazonAsin: 'B09XS7JWHH',
    amazonPriceAed: 1249,
    odooProductId: 102,
    isFeatured: true,
    isTrending: true,
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-08-18T15:30:00Z',
  },
  {
    id: 'prod-3',
    sku: 'MAC-M3P-16-1TB',
    barcode: '195949112984',
    title: 'Apple MacBook Pro 16" - M3 Pro (36GB Unified Memory, 1TB SSD)',
    slug: 'apple-macbook-pro-16-m3-pro',
    description:
      'Liquid Retina XDR display with extreme dynamic range. 12-core CPU and 18-core GPU powered by Apple M3 Pro silicon. Up to 22 hours of battery life with MagSafe 3 and studio-quality three-mic array with Arabic/English keyboard.',
    shortDescription: 'M3 Pro 12-Core, 36GB RAM, 1TB SSD, 16.2" Liquid Retina XDR.',
    category: 'Laptops',
    brand: 'Apple',
    basePriceAed: 10499,
    compareAtPriceAed: 11299,
    costPriceAed: 9200,
    featuredImage: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&auto=format&fit=crop&q=80',
    ],
    stock: 15,
    lowStockThreshold: 3,
    hasVariants: true,
    variants: [
      {
        id: 'var-3-1',
        sku: 'MAC-M3P-16-SB',
        name: 'Space Black / Arabic-English KB',
        options: { Color: 'Space Black', Keyboard: 'Arabic / English' },
        priceAdjustmentAed: 0,
        stock: 10,
      },
      {
        id: 'var-3-2',
        sku: 'MAC-M3P-16-SL',
        name: 'Silver / Arabic-English KB',
        options: { Color: 'Silver', Keyboard: 'Arabic / English' },
        priceAdjustmentAed: 0,
        stock: 5,
      },
    ],
    tags: ['MacBook', 'Creator', 'Apple Silicon', 'Workstation'],
    rating: 5.0,
    reviewCount: 61,
    amazonAsin: 'B0CM5N4Z8J',
    amazonPriceAed: 10899,
    odooProductId: 103,
    isFeatured: true,
    createdAt: '2026-02-15T09:00:00Z',
    updatedAt: '2026-08-19T10:00:00Z',
  },
  {
    id: 'prod-4',
    sku: 'SAM-S24U-512-TI',
    barcode: '8806095312049',
    title: 'Samsung Galaxy S24 Ultra 5G - 512GB (Titanium Gray)',
    slug: 'samsung-galaxy-s24-ultra-5g-512gb',
    description:
      'Galaxy AI is here. Circle to Search, Live Translate, Note Assist, and Photo Assist. Titanium exterior shield with built-in S Pen, 200MP camera sensor with ProVisual Engine, and Snapdragon 8 Gen 3 for Galaxy.',
    shortDescription: 'Galaxy AI, 200MP Quad Tele System, S Pen, Titanium Shield.',
    category: 'Smartphones',
    brand: 'Samsung',
    basePriceAed: 4399,
    compareAtPriceAed: 5099,
    costPriceAed: 3800,
    featuredImage: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80',
    ],
    stock: 18,
    lowStockThreshold: 4,
    hasVariants: false,
    variants: [],
    tags: ['Galaxy AI', 'Samsung', '5G', 'Android'],
    rating: 4.7,
    reviewCount: 88,
    amazonAsin: 'B0CSB45PZ8',
    amazonPriceAed: 4599,
    odooProductId: 104,
    isFlashDeal: true,
    flashDealEndsAt: new Date(Date.now() + 72 * 3600000).toISOString(),
    createdAt: '2026-03-01T11:00:00Z',
    updatedAt: '2026-08-21T14:00:00Z',
  },
  {
    id: 'prod-5',
    sku: 'DY-AIR-CP-BL',
    barcode: '5025155071289',
    title: 'Dyson Airwrap™ Multi-Styler Complete Long (Blue/Blush Edition)',
    slug: 'dyson-airwrap-multi-styler-complete-long',
    description:
      'Styles with air, not extreme heat. Re-engineered attachments harness Enhanced Coanda airflow to curl and shape in both directions, smooth flyaways, and create luxurious volume without heat damage. Includes travel pouch.',
    shortDescription: 'Coanda airflow styling, Intelligent heat control, Complete Long barrels.',
    category: 'Beauty & Lifestyle',
    brand: 'Dyson',
    basePriceAed: 2199,
    compareAtPriceAed: 2499,
    costPriceAed: 1800,
    featuredImage: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop&q=80',
    ],
    stock: 32,
    lowStockThreshold: 6,
    hasVariants: false,
    variants: [],
    tags: ['Luxury', 'Beauty', 'Hair Care', 'Gift'],
    rating: 4.9,
    reviewCount: 153,
    amazonAsin: 'B0B5FLM89P',
    amazonPriceAed: 2299,
    odooProductId: 105,
    isFeatured: true,
    createdAt: '2026-03-10T12:00:00Z',
    updatedAt: '2026-08-15T09:00:00Z',
  },
  {
    id: 'prod-6',
    sku: 'GAR-EPIX-PRO-47',
    barcode: '0753759324018',
    title: 'Garmin Epix Pro (Gen 2) Sapphire Edition 47mm Smartwatch',
    slug: 'garmin-epix-pro-gen-2-sapphire-47mm',
    description:
      'Stunning 1.3" AMOLED display with titanium bezel and scratch-resistant sapphire crystal. Built-in LED flashlight, multi-band GPS with SatIQ technology, 24/7 health tracking, preloaded TopoActive UAE & Gulf maps.',
    shortDescription: 'AMOLED Sapphire, Multi-band GPS, Built-in LED Flashlight, 16-day battery.',
    category: 'Wearables',
    brand: 'Garmin',
    basePriceAed: 3499,
    compareAtPriceAed: 3899,
    costPriceAed: 2900,
    featuredImage: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
    ],
    stock: 14,
    lowStockThreshold: 4,
    hasVariants: false,
    variants: [],
    tags: ['Smartwatch', 'Fitness', 'Outdoor', 'Titanium'],
    rating: 4.9,
    reviewCount: 42,
    amazonAsin: 'B0C4M6K89L',
    amazonPriceAed: 3649,
    odooProductId: 106,
    isTrending: true,
    createdAt: '2026-03-15T15:00:00Z',
    updatedAt: '2026-08-16T11:00:00Z',
  },
];

export const CATEGORIES = [
  'All Products',
  'Smartphones',
  'Laptops',
  'Audio',
  'Wearables',
  'Beauty & Lifestyle',
];

export const BRANDS = ['Apple', 'Sony', 'Samsung', 'Dyson', 'Garmin'];
