# The routes of the project.
#
# Each route describes how an incoming URL is going to be processed.

"https://{default}/":
    type: upstream
    upstream: "mymagento:php"

"http://{default}/":
    type: redirect
    to: "https://{default}/"
